[package]
name = "e2e-proc"
description = "End-to-end Testing Procedural Macros"
version = "0.1.0"
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
